# Generated by Django 2.2.19 on 2022-05-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
